# https://github.com/alacritty/alacritty#configuration

general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 2
y = 2

[font]
size = 10.0

[font.normal]
family = "FiraMono Nerd Font Mono Medium"
style = "Regular"

[font.bold]
family = "FiraMono Nerd Font Mono Medium"
style = "Bold"

[font.italic]
family = "FiraMono Nerd Font Mono Medium"
style = "Italic"

[font.bold_italic]
family = "FiraMono Nerd Font Mono Medium"
style = "Bold Italic"
