# modify this:
music_directory "~/Music"

# preferences
restore_paused "yes"
follow_inside_symlinks "yes"
follow_outside_symlonks "yes"

# do not touch these:
playlist_directory "~/.config/mpd/playlists"
db_file "~/.config/mpd/database"
log_file "~/.config/mpd/log"
pid_file "~/.config/mpd/pid"
state_file "~/.config/mpd/state"
sticker_file "~/.config/mpd/sticker.sql"
logl_evel "notice"
auto_update "yes"

# servicing to apps
# These two lines tell MPD where to listen for commands from your controller apps (like rmpc) 
# and how to keep those connections secure.
#
# To make the server discoverable from the outside, change the address to 0.0.0.0
# and it would also be better to put a password on it.
bind_to_address "127.0.0.1"
port "6600"

# audio specs
# (bridge between music player daemon mpd and computer sound card)
audio_output {
    type             "pipewire"
    name             "MPD PipeWire Sound Server"
}


# NOTE
# This is not a replacement for navidrome/Subsonic API
# MDP can stream the same audio to multiple devices at the same time
# without further config (meshing, but you need address 0.0.0.0) and works with clients
# such as "rmpc".


