[[manager.prepend_keymap]]
on   = "o"
run  = "quit"
desc = "Exit Yazi and CHANGE terminal directory"

[[manager.prepend_keymap]]
on   = "q"
run  = "quit --no-cwd-file"
desc = "Exit Yazi and KEEP original terminal directory"

[[manager.prepend_keymap]]
on   = "<C-c>"
run  = "quit --no-cwd-file"
desc = "Exit Yazi via Ctrl+C and KEEP original terminal directory"
