set -g mouse on
set -g escape-time 10
set -g update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"




# Load catpuccin mocha theme
set -g @catppuccin_flavor 'mocha'
# - force Catppuccin to use the actual window name string
set -ogq @catppuccin_window_text " #W"
set -ogq @catppuccin_window_default_text " #W"
set -ogq @catppuccin_window_current_text " #W"
# - customize the default (inactive) window colors
set -g @catppuccin_window_number_color "#{@thm_rosewater}"
set -g @catppuccin_window_text_color "#{@thm_surface_1}"
# - customize the current (active) window colors
set -g @catppuccin_window_current_number_color "#{@thm_peach}"
set -g @catppuccin_window_current_text_color "#{@thm_surface_1}"

# - load the plugin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Custom status bar
set -g status-position top

set -g status-left-length 100
set -g status-left ''
set -gaF status-left '#[fg=#{@thm_flamingo}]  #S  '

set -g status-right ''
set -gaF status-right '#[fg=#{@thm_peach}] %H:%M '
set -g status-right-length 100

# Dynamically darken active pane background only if more than 1 pane exists
# (Uses Catppuccin Mocha 'crust' #11111b for a darker look; swap hex if using another flavor)
set-hook -g window-layout-changed 'if-shell -F "#{>:#{window_panes},1}" "set -w window-active-style bg=#28283E" "set -w window-active-style bg=default"'

# Dividing lines
set -g pane-border-lines single
# - set the inactive pane dividing line to a muted surface color
set -g pane-border-style "fg=#{@thm_surface_0}"
# - set the active pane dividing line color to Catppuccin Peach
set -g pane-active-border-style "fg=#{@thm_surface_1},bg=#28283E"

# Message bar
set -g message-style "fg=#{@thm_subtext_0},bg=#{@thm_mantle}"

# Session and Windows selector list
set -g mode-style "fg=#{@thm_mantle},bg=#{@thm_peach}"



# custom bindings
# - reload configs
bind r {
  source-file ~/.tmux.conf
  display 'config reloaded'
}
# - equivalent to clear, but can do while a command is running
bind s send-keys -R Enter
# - equivalent to previous one, but also clears the history for that pane, so cannot scroll back
bind S {
  send-keys -R Enter
  clear-history
}

# hist and logs files
set -g history-file ~/.tmux_history
set-hook -g session-closed 'run-shell "echo \"Last session closed at \$(date)\" >> ~/.tmux_last_closed"'

