set -g default-terminal "screen-256color"
set -g status-bg colour94
set -g status-fg colour225

set -g mouse on

set-option -g escape-time 10

set-option -g update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"
